package au.edu.sydney.comp5703.cs30.chat.entity;

public class SeqIdGen {
    // Note: this simulates the id generated by database
    private long lastId = 0;

    public synchronized long getNextId() {
        long curr = lastId;
        lastId++;
        return curr;
    }
}
